### ISSUE TITLE
How to get the final schedule?

### ISSUE THREAD

**Issue by chandanavgermany** [zcajiayin/L2D#1]
Hi, 

I have gone through your paper and code as well, It's very good.  I have a question. How to get the obtained schedule from RL agent?

**Comment by zcajiayin** [comment]
you can find the start time for each operation by:
`env.LBs.reshape(n_job, n_machine)`

**Comment by chandanavgermany** [comment]
Hi,

Thanks it's working !!

**Comment by chandanavgermany** [comment]
One More Question @zcajiayin, you can check from the following link,
https://github.com/chandanavgermany/Job_Shop_Scheduling_using_Simulated_Annealing/blob/master/data.txt
its a 10*10 problem where for each operation point there will be a specific machine to process it. Is this case considered in your code? if not Could you please let me know how can I do it?

**Comment by zcajiayin** [comment]
Yes, I think so. But you should be aware of two things:
1). the underline distribution from which this instance is drawn. If the distribution is not the same as what we used in our paper, the performance of our method may vary;
2). Since you are using a neighbourhood search method, i.e. Simulated annealing (SA), comparing our method maybe not fair since we are a one-shot constructive process. For detail, please refer to author response of our paper.

**Comment by chandanavgermany** [comment]
Yeah, I have noticed distribution-related dependency. I will give it a try for operation-specific machines during the weekend.
